// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, CAPigeonSensorPosition) {
  CAPigeonSensorPositionBack = 0,
  CAPigeonSensorPositionFront = 1,
  CAPigeonSensorPositionUnknown = 2,
  CAPigeonSensorPositionExternal = 3,
};

/// Wrapper for CAPigeonSensorPosition to allow for nullability.
@interface CAPigeonSensorPositionBox : NSObject
@property(nonatomic, assign) CAPigeonSensorPosition value;
- (instancetype)initWithValue:(CAPigeonSensorPosition)value;
@end

/// Video recording quality, from [sd] to [uhd], with [highest] and [lowest] to
/// let the device choose the best/worst quality available.
/// [highest] is the default quality.
///
/// Qualities are defined like this:
/// [sd] < [hd] < [fhd] < [uhd]
typedef NS_ENUM(NSUInteger, CAVideoRecordingQuality) {
  CAVideoRecordingQualityLowest = 0,
  CAVideoRecordingQualitySd = 1,
  CAVideoRecordingQualityHd = 2,
  CAVideoRecordingQualityFhd = 3,
  CAVideoRecordingQualityUhd = 4,
  CAVideoRecordingQualityHighest = 5,
};

/// Wrapper for CAVideoRecordingQuality to allow for nullability.
@interface CAVideoRecordingQualityBox : NSObject
@property(nonatomic, assign) CAVideoRecordingQuality value;
- (instancetype)initWithValue:(CAVideoRecordingQuality)value;
@end

/// If the specified [VideoRecordingQuality] is not available on the device,
/// the [VideoRecordingQuality] will fallback to [higher] or [lower] quality.
/// [higher] is the default fallback strategy.
typedef NS_ENUM(NSUInteger, CAQualityFallbackStrategy) {
  CAQualityFallbackStrategyHigher = 0,
  CAQualityFallbackStrategyLower = 1,
};

/// Wrapper for CAQualityFallbackStrategy to allow for nullability.
@interface CAQualityFallbackStrategyBox : NSObject
@property(nonatomic, assign) CAQualityFallbackStrategy value;
- (instancetype)initWithValue:(CAQualityFallbackStrategy)value;
@end

typedef NS_ENUM(NSUInteger, CACupertinoFileType) {
  CACupertinoFileTypeQuickTimeMovie = 0,
  CACupertinoFileTypeMpeg4 = 1,
  CACupertinoFileTypeAppleM4V = 2,
  CACupertinoFileTypeType3GPP = 3,
  CACupertinoFileTypeType3GPP2 = 4,
};

/// Wrapper for CACupertinoFileType to allow for nullability.
@interface CACupertinoFileTypeBox : NSObject
@property(nonatomic, assign) CACupertinoFileType value;
- (instancetype)initWithValue:(CACupertinoFileType)value;
@end

typedef NS_ENUM(NSUInteger, CACupertinoCodecType) {
  CACupertinoCodecTypeH264 = 0,
  CACupertinoCodecTypeHevc = 1,
  CACupertinoCodecTypeHevcWithAlpha = 2,
  CACupertinoCodecTypeJpeg = 3,
  CACupertinoCodecTypeAppleProRes4444 = 4,
  CACupertinoCodecTypeAppleProRes422 = 5,
  CACupertinoCodecTypeAppleProRes422HQ = 6,
  CACupertinoCodecTypeAppleProRes422LT = 7,
  CACupertinoCodecTypeAppleProRes422Proxy = 8,
};

/// Wrapper for CACupertinoCodecType to allow for nullability.
@interface CACupertinoCodecTypeBox : NSObject
@property(nonatomic, assign) CACupertinoCodecType value;
- (instancetype)initWithValue:(CACupertinoCodecType)value;
@end

typedef NS_ENUM(NSUInteger, CAPigeonSensorType) {
  /// A built-in wide-angle camera.
  ///
  /// The wide angle sensor is the default sensor for iOS
  CAPigeonSensorTypeWideAngle = 0,
  /// A built-in camera with a shorter focal length than that of the wide-angle camera.
  CAPigeonSensorTypeUltraWideAngle = 1,
  /// A built-in camera device with a longer focal length than the wide-angle camera.
  CAPigeonSensorTypeTelephoto = 2,
  /// A device that consists of two cameras, one Infrared and one YUV.
  ///
  /// iOS only
  CAPigeonSensorTypeTrueDepth = 3,
  CAPigeonSensorTypeUnknown = 4,
};

/// Wrapper for CAPigeonSensorType to allow for nullability.
@interface CAPigeonSensorTypeBox : NSObject
@property(nonatomic, assign) CAPigeonSensorType value;
- (instancetype)initWithValue:(CAPigeonSensorType)value;
@end

typedef NS_ENUM(NSUInteger, CACamerAwesomePermission) {
  CACamerAwesomePermissionStorage = 0,
  CACamerAwesomePermissionCamera = 1,
  CACamerAwesomePermissionLocation = 2,
  CACamerAwesomePermissionRecord_audio = 3,
};

/// Wrapper for CACamerAwesomePermission to allow for nullability.
@interface CACamerAwesomePermissionBox : NSObject
@property(nonatomic, assign) CACamerAwesomePermission value;
- (instancetype)initWithValue:(CACamerAwesomePermission)value;
@end

typedef NS_ENUM(NSUInteger, CAAnalysisImageFormat) {
  CAAnalysisImageFormatYuv_420 = 0,
  CAAnalysisImageFormatBgra8888 = 1,
  CAAnalysisImageFormatJpeg = 2,
  CAAnalysisImageFormatNv21 = 3,
  CAAnalysisImageFormatUnknown = 4,
};

/// Wrapper for CAAnalysisImageFormat to allow for nullability.
@interface CAAnalysisImageFormatBox : NSObject
@property(nonatomic, assign) CAAnalysisImageFormat value;
- (instancetype)initWithValue:(CAAnalysisImageFormat)value;
@end

typedef NS_ENUM(NSUInteger, CAAnalysisRotation) {
  CAAnalysisRotationRotation0deg = 0,
  CAAnalysisRotationRotation90deg = 1,
  CAAnalysisRotationRotation180deg = 2,
  CAAnalysisRotationRotation270deg = 3,
};

/// Wrapper for CAAnalysisRotation to allow for nullability.
@interface CAAnalysisRotationBox : NSObject
@property(nonatomic, assign) CAAnalysisRotation value;
- (instancetype)initWithValue:(CAAnalysisRotation)value;
@end

@class CAPreviewSize;
@class CAExifPreferences;
@class CAPigeonSensor;
@class CAVideoOptions;
@class CAAndroidVideoOptions;
@class CACupertinoVideoOptions;
@class CAPigeonSensorTypeDevice;
@class CAAndroidFocusSettings;
@class CAPlaneWrapper;
@class CACropRectWrapper;
@class CAAnalysisImageWrapper;

@interface CAPreviewSize : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithWidth:(double )width
    height:(double )height;
@property(nonatomic, assign) double  width;
@property(nonatomic, assign) double  height;
@end

@interface CAExifPreferences : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSaveGPSLocation:(BOOL )saveGPSLocation;
@property(nonatomic, assign) BOOL  saveGPSLocation;
@end

@interface CAPigeonSensor : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPosition:(CAPigeonSensorPosition)position
    type:(CAPigeonSensorType)type
    deviceId:(nullable NSString *)deviceId
    zoomFactor:(nullable NSNumber *)zoomFactor;
@property(nonatomic, assign) CAPigeonSensorPosition position;
@property(nonatomic, assign) CAPigeonSensorType type;
@property(nonatomic, copy, nullable) NSString * deviceId;
@property(nonatomic, strong, nullable) NSNumber * zoomFactor;
@end

/// Video recording options. Some of them are specific to each platform.
@interface CAVideoOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableAudio:(BOOL )enableAudio
    quality:(nullable CAVideoRecordingQualityBox *)quality
    android:(nullable CAAndroidVideoOptions *)android
    ios:(nullable CACupertinoVideoOptions *)ios;
/// Enable audio while video recording
@property(nonatomic, assign) BOOL  enableAudio;
/// The quality of the video recording, defaults to [VideoRecordingQuality.highest].
@property(nonatomic, strong, nullable) CAVideoRecordingQualityBox * quality;
@property(nonatomic, strong, nullable) CAAndroidVideoOptions * android;
@property(nonatomic, strong, nullable) CACupertinoVideoOptions * ios;
@end

@interface CAAndroidVideoOptions : NSObject
+ (instancetype)makeWithBitrate:(nullable NSNumber *)bitrate
    fallbackStrategy:(nullable CAQualityFallbackStrategyBox *)fallbackStrategy;
/// The bitrate of the video recording. Only set it if a custom bitrate is
/// desired.
@property(nonatomic, strong, nullable) NSNumber * bitrate;
@property(nonatomic, strong, nullable) CAQualityFallbackStrategyBox * fallbackStrategy;
@end

@interface CACupertinoVideoOptions : NSObject
+ (instancetype)makeWithFileType:(nullable CACupertinoFileTypeBox *)fileType
    codec:(nullable CACupertinoCodecTypeBox *)codec
    fps:(nullable NSNumber *)fps;
/// Specify video file type, defaults to [AVFileTypeQuickTimeMovie].
@property(nonatomic, strong, nullable) CACupertinoFileTypeBox * fileType;
/// Specify video codec, defaults to [AVVideoCodecTypeH264].
@property(nonatomic, strong, nullable) CACupertinoCodecTypeBox * codec;
/// Specify video fps, defaults to [30].
@property(nonatomic, strong, nullable) NSNumber * fps;
@end

@interface CAPigeonSensorTypeDevice : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSensorType:(CAPigeonSensorType)sensorType
    name:(NSString *)name
    iso:(double )iso
    flashAvailable:(BOOL )flashAvailable
    uid:(NSString *)uid
    zoomFactor:(nullable NSNumber *)zoomFactor;
@property(nonatomic, assign) CAPigeonSensorType sensorType;
/// A localized device name for display in the user interface.
@property(nonatomic, copy) NSString * name;
/// The current exposure ISO value.
@property(nonatomic, assign) double  iso;
/// A Boolean value that indicates whether the flash is currently available for use.
@property(nonatomic, assign) BOOL  flashAvailable;
/// An identifier that uniquely identifies the device.
@property(nonatomic, copy) NSString * uid;
/// The zoom factor relative to the wide-angle camera.
@property(nonatomic, strong, nullable) NSNumber * zoomFactor;
@end

@interface CAAndroidFocusSettings : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAutoCancelDurationInMillis:(NSInteger )autoCancelDurationInMillis;
/// The auto focus will be canceled after the given [autoCancelDurationInMillis].
/// If [autoCancelDurationInMillis] is equals to 0 (or less), the auto focus
/// will **not** be canceled. A manual `focusOnPoint` call will be needed to
/// focus on an other point.
/// Minimal duration of [autoCancelDurationInMillis] is 1000 ms. If set
/// between 0 (exclusive) and 1000 (exclusive), it will be raised to 1000.
@property(nonatomic, assign) NSInteger  autoCancelDurationInMillis;
@end

@interface CAPlaneWrapper : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithBytes:(FlutterStandardTypedData *)bytes
    bytesPerRow:(NSInteger )bytesPerRow
    bytesPerPixel:(nullable NSNumber *)bytesPerPixel
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height;
@property(nonatomic, strong) FlutterStandardTypedData * bytes;
@property(nonatomic, assign) NSInteger  bytesPerRow;
@property(nonatomic, strong, nullable) NSNumber * bytesPerPixel;
@property(nonatomic, strong, nullable) NSNumber * width;
@property(nonatomic, strong, nullable) NSNumber * height;
@end

@interface CACropRectWrapper : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLeft:(NSInteger )left
    top:(NSInteger )top
    width:(NSInteger )width
    height:(NSInteger )height;
@property(nonatomic, assign) NSInteger  left;
@property(nonatomic, assign) NSInteger  top;
@property(nonatomic, assign) NSInteger  width;
@property(nonatomic, assign) NSInteger  height;
@end

@interface CAAnalysisImageWrapper : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithFormat:(CAAnalysisImageFormat)format
    bytes:(nullable FlutterStandardTypedData *)bytes
    width:(NSInteger )width
    height:(NSInteger )height
    planes:(nullable NSArray<CAPlaneWrapper *> *)planes
    cropRect:(nullable CACropRectWrapper *)cropRect
    rotation:(nullable CAAnalysisRotationBox *)rotation;
@property(nonatomic, assign) CAAnalysisImageFormat format;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * bytes;
@property(nonatomic, assign) NSInteger  width;
@property(nonatomic, assign) NSInteger  height;
@property(nonatomic, copy, nullable) NSArray<CAPlaneWrapper *> * planes;
@property(nonatomic, strong, nullable) CACropRectWrapper * cropRect;
@property(nonatomic, strong, nullable) CAAnalysisRotationBox * rotation;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *CAGetPigeonCodec(void);

@protocol CAAnalysisImageUtils
- (void)nv21toJpegNv21Image:(CAAnalysisImageWrapper *)nv21Image jpegQuality:(NSInteger)jpegQuality completion:(void (^)(CAAnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
- (void)yuv420toJpegYuvImage:(CAAnalysisImageWrapper *)yuvImage jpegQuality:(NSInteger)jpegQuality completion:(void (^)(CAAnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
- (void)yuv420toNv21YuvImage:(CAAnalysisImageWrapper *)yuvImage completion:(void (^)(CAAnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
- (void)bgra8888toJpegBgra8888image:(CAAnalysisImageWrapper *)bgra8888image jpegQuality:(NSInteger)jpegQuality completion:(void (^)(CAAnalysisImageWrapper *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpCAAnalysisImageUtils(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CAAnalysisImageUtils> *_Nullable api);

extern void SetUpCAAnalysisImageUtilsWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CAAnalysisImageUtils> *_Nullable api, NSString *messageChannelSuffix);


@protocol CACameraInterface
- (void)setupCameraSensors:(NSArray<CAPigeonSensor *> *)sensors aspectRatio:(NSString *)aspectRatio zoom:(double)zoom mirrorFrontCamera:(BOOL)mirrorFrontCamera enablePhysicalButton:(BOOL)enablePhysicalButton flashMode:(NSString *)flashMode captureMode:(NSString *)captureMode enableImageStream:(BOOL)enableImageStream exifPreferences:(CAExifPreferences *)exifPreferences videoOptions:(nullable CAVideoOptions *)videoOptions completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSString *> *)checkPermissionsPermissions:(NSArray<NSString *> *)permissions error:(FlutterError *_Nullable *_Nonnull)error;
/// Returns given [CamerAwesomePermission] list (as String). Location permission might be
/// refused but the app should still be able to run.
- (void)requestPermissionsSaveGpsLocation:(BOOL)saveGpsLocation completion:(void (^)(NSArray<NSString *> *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getPreviewTextureIdCameraPosition:(NSInteger)cameraPosition error:(FlutterError *_Nullable *_Nonnull)error;
- (void)takePhotoSensors:(NSArray<CAPigeonSensor *> *)sensors paths:(NSArray<NSString *> *)paths completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)recordVideoSensors:(NSArray<CAPigeonSensor *> *)sensors paths:(NSArray<NSString *> *)paths completion:(void (^)(FlutterError *_Nullable))completion;
- (void)pauseVideoRecordingWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)resumeVideoRecordingWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)receivedImageFromStreamWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopRecordingVideoWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<CAPigeonSensorTypeDevice *> *)getFrontSensorsWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<CAPigeonSensorTypeDevice *> *)getBackSensorsWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)startWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)stopWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setFlashModeMode:(NSString *)mode error:(FlutterError *_Nullable *_Nonnull)error;
- (void)handleAutoFocusWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Starts auto focus on a point at ([x], [y]).
///
/// On Android, you can control after how much time you want to switch back
/// to passive focus mode with [androidFocusSettings].
- (void)focusOnPointPreviewSize:(CAPreviewSize *)previewSize x:(double)x y:(double)y androidFocusSettings:(nullable CAAndroidFocusSettings *)androidFocusSettings error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setZoomZoom:(double)zoom error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMirrorFrontCameraMirror:(BOOL)mirror error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setSensorSensors:(NSArray<CAPigeonSensor *> *)sensors error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setCorrectionBrightness:(double)brightness error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMinZoomWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getMaxZoomWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setCaptureModeMode:(NSString *)mode error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setRecordingAudioModeEnableAudio:(BOOL)enableAudio completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<CAPreviewSize *> *)availableSizesWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)refreshWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable CAPreviewSize *)getEffectivPreviewSizeIndex:(NSInteger)index error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPhotoSizeSize:(CAPreviewSize *)size error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPreviewSizeSize:(CAPreviewSize *)size error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setAspectRatioAspectRatio:(NSString *)aspectRatio error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setupImageAnalysisStreamFormat:(NSString *)format width:(NSInteger)width maxFramesPerSecond:(nullable NSNumber *)maxFramesPerSecond autoStart:(BOOL)autoStart error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setExifPreferencesExifPreferences:(CAExifPreferences *)exifPreferences completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)startAnalysisWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopAnalysisWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setFilterMatrix:(FlutterStandardTypedData *)matrix error:(FlutterError *_Nullable *_Nonnull)error;
- (void)isVideoRecordingAndImageAnalysisSupportedSensor:(CAPigeonSensorPosition)sensor completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isMultiCamSupportedWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpCACameraInterface(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CACameraInterface> *_Nullable api);

extern void SetUpCACameraInterfaceWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CACameraInterface> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
