// Autogenerated from Pigeon (v21.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation CAPigeonSensorPositionBox
- (instancetype)initWithValue:(CAPigeonSensorPosition)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

/// Video recording quality, from [sd] to [uhd], with [highest] and [lowest] to
/// let the device choose the best/worst quality available.
/// [highest] is the default quality.
///
/// Qualities are defined like this:
/// [sd] < [hd] < [fhd] < [uhd]
@implementation CAVideoRecordingQualityBox
- (instancetype)initWithValue:(CAVideoRecordingQuality)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

/// If the specified [VideoRecordingQuality] is not available on the device,
/// the [VideoRecordingQuality] will fallback to [higher] or [lower] quality.
/// [higher] is the default fallback strategy.
@implementation CAQualityFallbackStrategyBox
- (instancetype)initWithValue:(CAQualityFallbackStrategy)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CACupertinoFileTypeBox
- (instancetype)initWithValue:(CACupertinoFileType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CACupertinoCodecTypeBox
- (instancetype)initWithValue:(CACupertinoCodecType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CAPigeonSensorTypeBox
- (instancetype)initWithValue:(CAPigeonSensorType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CACamerAwesomePermissionBox
- (instancetype)initWithValue:(CACamerAwesomePermission)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CAAnalysisImageFormatBox
- (instancetype)initWithValue:(CAAnalysisImageFormat)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CAAnalysisRotationBox
- (instancetype)initWithValue:(CAAnalysisRotation)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface CAPreviewSize ()
+ (CAPreviewSize *)fromList:(NSArray<id> *)list;
+ (nullable CAPreviewSize *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAExifPreferences ()
+ (CAExifPreferences *)fromList:(NSArray<id> *)list;
+ (nullable CAExifPreferences *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAPigeonSensor ()
+ (CAPigeonSensor *)fromList:(NSArray<id> *)list;
+ (nullable CAPigeonSensor *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAVideoOptions ()
+ (CAVideoOptions *)fromList:(NSArray<id> *)list;
+ (nullable CAVideoOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAAndroidVideoOptions ()
+ (CAAndroidVideoOptions *)fromList:(NSArray<id> *)list;
+ (nullable CAAndroidVideoOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CACupertinoVideoOptions ()
+ (CACupertinoVideoOptions *)fromList:(NSArray<id> *)list;
+ (nullable CACupertinoVideoOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAPigeonSensorTypeDevice ()
+ (CAPigeonSensorTypeDevice *)fromList:(NSArray<id> *)list;
+ (nullable CAPigeonSensorTypeDevice *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAAndroidFocusSettings ()
+ (CAAndroidFocusSettings *)fromList:(NSArray<id> *)list;
+ (nullable CAAndroidFocusSettings *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAPlaneWrapper ()
+ (CAPlaneWrapper *)fromList:(NSArray<id> *)list;
+ (nullable CAPlaneWrapper *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CACropRectWrapper ()
+ (CACropRectWrapper *)fromList:(NSArray<id> *)list;
+ (nullable CACropRectWrapper *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CAAnalysisImageWrapper ()
+ (CAAnalysisImageWrapper *)fromList:(NSArray<id> *)list;
+ (nullable CAAnalysisImageWrapper *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation CAPreviewSize
+ (instancetype)makeWithWidth:(double )width
    height:(double )height {
  CAPreviewSize* pigeonResult = [[CAPreviewSize alloc] init];
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (CAPreviewSize *)fromList:(NSArray<id> *)list {
  CAPreviewSize *pigeonResult = [[CAPreviewSize alloc] init];
  pigeonResult.width = [GetNullableObjectAtIndex(list, 0) doubleValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 1) doubleValue];
  return pigeonResult;
}
+ (nullable CAPreviewSize *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAPreviewSize fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.width),
    @(self.height),
  ];
}
@end

@implementation CAExifPreferences
+ (instancetype)makeWithSaveGPSLocation:(BOOL )saveGPSLocation {
  CAExifPreferences* pigeonResult = [[CAExifPreferences alloc] init];
  pigeonResult.saveGPSLocation = saveGPSLocation;
  return pigeonResult;
}
+ (CAExifPreferences *)fromList:(NSArray<id> *)list {
  CAExifPreferences *pigeonResult = [[CAExifPreferences alloc] init];
  pigeonResult.saveGPSLocation = [GetNullableObjectAtIndex(list, 0) boolValue];
  return pigeonResult;
}
+ (nullable CAExifPreferences *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAExifPreferences fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.saveGPSLocation),
  ];
}
@end

@implementation CAPigeonSensor
+ (instancetype)makeWithPosition:(CAPigeonSensorPosition)position
    type:(CAPigeonSensorType)type
    deviceId:(nullable NSString *)deviceId
    zoomFactor:(nullable NSNumber *)zoomFactor {
  CAPigeonSensor* pigeonResult = [[CAPigeonSensor alloc] init];
  pigeonResult.position = position;
  pigeonResult.type = type;
  pigeonResult.deviceId = deviceId;
  pigeonResult.zoomFactor = zoomFactor;
  return pigeonResult;
}
+ (CAPigeonSensor *)fromList:(NSArray<id> *)list {
  CAPigeonSensor *pigeonResult = [[CAPigeonSensor alloc] init];
  CAPigeonSensorPositionBox *boxedCAPigeonSensorPosition = GetNullableObjectAtIndex(list, 0);
  pigeonResult.position = boxedCAPigeonSensorPosition.value;
  CAPigeonSensorTypeBox *boxedCAPigeonSensorType = GetNullableObjectAtIndex(list, 1);
  pigeonResult.type = boxedCAPigeonSensorType.value;
  pigeonResult.deviceId = GetNullableObjectAtIndex(list, 2);
  pigeonResult.zoomFactor = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable CAPigeonSensor *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAPigeonSensor fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[CAPigeonSensorPositionBox alloc] initWithValue:self.position],
    [[CAPigeonSensorTypeBox alloc] initWithValue:self.type],
    self.deviceId ?: [NSNull null],
    self.zoomFactor ?: [NSNull null],
  ];
}
@end

@implementation CAVideoOptions
+ (instancetype)makeWithEnableAudio:(BOOL )enableAudio
    quality:(nullable CAVideoRecordingQualityBox *)quality
    android:(nullable CAAndroidVideoOptions *)android
    ios:(nullable CACupertinoVideoOptions *)ios {
  CAVideoOptions* pigeonResult = [[CAVideoOptions alloc] init];
  pigeonResult.enableAudio = enableAudio;
  pigeonResult.quality = quality;
  pigeonResult.android = android;
  pigeonResult.ios = ios;
  return pigeonResult;
}
+ (CAVideoOptions *)fromList:(NSArray<id> *)list {
  CAVideoOptions *pigeonResult = [[CAVideoOptions alloc] init];
  pigeonResult.enableAudio = [GetNullableObjectAtIndex(list, 0) boolValue];
  pigeonResult.quality = GetNullableObjectAtIndex(list, 1);
  pigeonResult.android = GetNullableObjectAtIndex(list, 2);
  pigeonResult.ios = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable CAVideoOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAVideoOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.enableAudio),
    self.quality ?: [NSNull null],
    self.android ?: [NSNull null],
    self.ios ?: [NSNull null],
  ];
}
@end

@implementation CAAndroidVideoOptions
+ (instancetype)makeWithBitrate:(nullable NSNumber *)bitrate
    fallbackStrategy:(nullable CAQualityFallbackStrategyBox *)fallbackStrategy {
  CAAndroidVideoOptions* pigeonResult = [[CAAndroidVideoOptions alloc] init];
  pigeonResult.bitrate = bitrate;
  pigeonResult.fallbackStrategy = fallbackStrategy;
  return pigeonResult;
}
+ (CAAndroidVideoOptions *)fromList:(NSArray<id> *)list {
  CAAndroidVideoOptions *pigeonResult = [[CAAndroidVideoOptions alloc] init];
  pigeonResult.bitrate = GetNullableObjectAtIndex(list, 0);
  pigeonResult.fallbackStrategy = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable CAAndroidVideoOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAAndroidVideoOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.bitrate ?: [NSNull null],
    self.fallbackStrategy ?: [NSNull null],
  ];
}
@end

@implementation CACupertinoVideoOptions
+ (instancetype)makeWithFileType:(nullable CACupertinoFileTypeBox *)fileType
    codec:(nullable CACupertinoCodecTypeBox *)codec
    fps:(nullable NSNumber *)fps {
  CACupertinoVideoOptions* pigeonResult = [[CACupertinoVideoOptions alloc] init];
  pigeonResult.fileType = fileType;
  pigeonResult.codec = codec;
  pigeonResult.fps = fps;
  return pigeonResult;
}
+ (CACupertinoVideoOptions *)fromList:(NSArray<id> *)list {
  CACupertinoVideoOptions *pigeonResult = [[CACupertinoVideoOptions alloc] init];
  pigeonResult.fileType = GetNullableObjectAtIndex(list, 0);
  pigeonResult.codec = GetNullableObjectAtIndex(list, 1);
  pigeonResult.fps = GetNullableObjectAtIndex(list, 2);
  return pigeonResult;
}
+ (nullable CACupertinoVideoOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CACupertinoVideoOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.fileType ?: [NSNull null],
    self.codec ?: [NSNull null],
    self.fps ?: [NSNull null],
  ];
}
@end

@implementation CAPigeonSensorTypeDevice
+ (instancetype)makeWithSensorType:(CAPigeonSensorType)sensorType
    name:(NSString *)name
    iso:(double )iso
    flashAvailable:(BOOL )flashAvailable
    uid:(NSString *)uid
    zoomFactor:(nullable NSNumber *)zoomFactor {
  CAPigeonSensorTypeDevice* pigeonResult = [[CAPigeonSensorTypeDevice alloc] init];
  pigeonResult.sensorType = sensorType;
  pigeonResult.name = name;
  pigeonResult.iso = iso;
  pigeonResult.flashAvailable = flashAvailable;
  pigeonResult.uid = uid;
  pigeonResult.zoomFactor = zoomFactor;
  return pigeonResult;
}
+ (CAPigeonSensorTypeDevice *)fromList:(NSArray<id> *)list {
  CAPigeonSensorTypeDevice *pigeonResult = [[CAPigeonSensorTypeDevice alloc] init];
  CAPigeonSensorTypeBox *boxedCAPigeonSensorType = GetNullableObjectAtIndex(list, 0);
  pigeonResult.sensorType = boxedCAPigeonSensorType.value;
  pigeonResult.name = GetNullableObjectAtIndex(list, 1);
  pigeonResult.iso = [GetNullableObjectAtIndex(list, 2) doubleValue];
  pigeonResult.flashAvailable = [GetNullableObjectAtIndex(list, 3) boolValue];
  pigeonResult.uid = GetNullableObjectAtIndex(list, 4);
  pigeonResult.zoomFactor = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable CAPigeonSensorTypeDevice *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAPigeonSensorTypeDevice fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[CAPigeonSensorTypeBox alloc] initWithValue:self.sensorType],
    self.name ?: [NSNull null],
    @(self.iso),
    @(self.flashAvailable),
    self.uid ?: [NSNull null],
    self.zoomFactor ?: [NSNull null],
  ];
}
@end

@implementation CAAndroidFocusSettings
+ (instancetype)makeWithAutoCancelDurationInMillis:(NSInteger )autoCancelDurationInMillis {
  CAAndroidFocusSettings* pigeonResult = [[CAAndroidFocusSettings alloc] init];
  pigeonResult.autoCancelDurationInMillis = autoCancelDurationInMillis;
  return pigeonResult;
}
+ (CAAndroidFocusSettings *)fromList:(NSArray<id> *)list {
  CAAndroidFocusSettings *pigeonResult = [[CAAndroidFocusSettings alloc] init];
  pigeonResult.autoCancelDurationInMillis = [GetNullableObjectAtIndex(list, 0) integerValue];
  return pigeonResult;
}
+ (nullable CAAndroidFocusSettings *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAAndroidFocusSettings fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.autoCancelDurationInMillis),
  ];
}
@end

@implementation CAPlaneWrapper
+ (instancetype)makeWithBytes:(FlutterStandardTypedData *)bytes
    bytesPerRow:(NSInteger )bytesPerRow
    bytesPerPixel:(nullable NSNumber *)bytesPerPixel
    width:(nullable NSNumber *)width
    height:(nullable NSNumber *)height {
  CAPlaneWrapper* pigeonResult = [[CAPlaneWrapper alloc] init];
  pigeonResult.bytes = bytes;
  pigeonResult.bytesPerRow = bytesPerRow;
  pigeonResult.bytesPerPixel = bytesPerPixel;
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (CAPlaneWrapper *)fromList:(NSArray<id> *)list {
  CAPlaneWrapper *pigeonResult = [[CAPlaneWrapper alloc] init];
  pigeonResult.bytes = GetNullableObjectAtIndex(list, 0);
  pigeonResult.bytesPerRow = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.bytesPerPixel = GetNullableObjectAtIndex(list, 2);
  pigeonResult.width = GetNullableObjectAtIndex(list, 3);
  pigeonResult.height = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable CAPlaneWrapper *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAPlaneWrapper fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.bytes ?: [NSNull null],
    @(self.bytesPerRow),
    self.bytesPerPixel ?: [NSNull null],
    self.width ?: [NSNull null],
    self.height ?: [NSNull null],
  ];
}
@end

@implementation CACropRectWrapper
+ (instancetype)makeWithLeft:(NSInteger )left
    top:(NSInteger )top
    width:(NSInteger )width
    height:(NSInteger )height {
  CACropRectWrapper* pigeonResult = [[CACropRectWrapper alloc] init];
  pigeonResult.left = left;
  pigeonResult.top = top;
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (CACropRectWrapper *)fromList:(NSArray<id> *)list {
  CACropRectWrapper *pigeonResult = [[CACropRectWrapper alloc] init];
  pigeonResult.left = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.top = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.width = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 3) integerValue];
  return pigeonResult;
}
+ (nullable CACropRectWrapper *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CACropRectWrapper fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.left),
    @(self.top),
    @(self.width),
    @(self.height),
  ];
}
@end

@implementation CAAnalysisImageWrapper
+ (instancetype)makeWithFormat:(CAAnalysisImageFormat)format
    bytes:(nullable FlutterStandardTypedData *)bytes
    width:(NSInteger )width
    height:(NSInteger )height
    planes:(nullable NSArray<CAPlaneWrapper *> *)planes
    cropRect:(nullable CACropRectWrapper *)cropRect
    rotation:(nullable CAAnalysisRotationBox *)rotation {
  CAAnalysisImageWrapper* pigeonResult = [[CAAnalysisImageWrapper alloc] init];
  pigeonResult.format = format;
  pigeonResult.bytes = bytes;
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.planes = planes;
  pigeonResult.cropRect = cropRect;
  pigeonResult.rotation = rotation;
  return pigeonResult;
}
+ (CAAnalysisImageWrapper *)fromList:(NSArray<id> *)list {
  CAAnalysisImageWrapper *pigeonResult = [[CAAnalysisImageWrapper alloc] init];
  CAAnalysisImageFormatBox *boxedCAAnalysisImageFormat = GetNullableObjectAtIndex(list, 0);
  pigeonResult.format = boxedCAAnalysisImageFormat.value;
  pigeonResult.bytes = GetNullableObjectAtIndex(list, 1);
  pigeonResult.width = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 3) integerValue];
  pigeonResult.planes = GetNullableObjectAtIndex(list, 4);
  pigeonResult.cropRect = GetNullableObjectAtIndex(list, 5);
  pigeonResult.rotation = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable CAAnalysisImageWrapper *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CAAnalysisImageWrapper fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[CAAnalysisImageFormatBox alloc] initWithValue:self.format],
    self.bytes ?: [NSNull null],
    @(self.width),
    @(self.height),
    self.planes ?: [NSNull null],
    self.cropRect ?: [NSNull null],
    self.rotation ?: [NSNull null],
  ];
}
@end

@interface CAPigeonPigeonCodecReader : FlutterStandardReader
@end
@implementation CAPigeonPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CAPigeonSensorPositionBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CAVideoRecordingQualityBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CAQualityFallbackStrategyBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 132: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CACupertinoFileTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 133: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CACupertinoCodecTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 134: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CAPigeonSensorTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 135: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CACamerAwesomePermissionBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 136: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CAAnalysisImageFormatBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 137: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[CAAnalysisRotationBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 138: 
      return [CAPreviewSize fromList:[self readValue]];
    case 139: 
      return [CAExifPreferences fromList:[self readValue]];
    case 140: 
      return [CAPigeonSensor fromList:[self readValue]];
    case 141: 
      return [CAVideoOptions fromList:[self readValue]];
    case 142: 
      return [CAAndroidVideoOptions fromList:[self readValue]];
    case 143: 
      return [CACupertinoVideoOptions fromList:[self readValue]];
    case 144: 
      return [CAPigeonSensorTypeDevice fromList:[self readValue]];
    case 145: 
      return [CAAndroidFocusSettings fromList:[self readValue]];
    case 146: 
      return [CAPlaneWrapper fromList:[self readValue]];
    case 147: 
      return [CACropRectWrapper fromList:[self readValue]];
    case 148: 
      return [CAAnalysisImageWrapper fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface CAPigeonPigeonCodecWriter : FlutterStandardWriter
@end
@implementation CAPigeonPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[CAPigeonSensorPositionBox class]]) {
    CAPigeonSensorPositionBox *box = (CAPigeonSensorPositionBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CAVideoRecordingQualityBox class]]) {
    CAVideoRecordingQualityBox *box = (CAVideoRecordingQualityBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CAQualityFallbackStrategyBox class]]) {
    CAQualityFallbackStrategyBox *box = (CAQualityFallbackStrategyBox *)value;
    [self writeByte:131];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CACupertinoFileTypeBox class]]) {
    CACupertinoFileTypeBox *box = (CACupertinoFileTypeBox *)value;
    [self writeByte:132];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CACupertinoCodecTypeBox class]]) {
    CACupertinoCodecTypeBox *box = (CACupertinoCodecTypeBox *)value;
    [self writeByte:133];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CAPigeonSensorTypeBox class]]) {
    CAPigeonSensorTypeBox *box = (CAPigeonSensorTypeBox *)value;
    [self writeByte:134];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CACamerAwesomePermissionBox class]]) {
    CACamerAwesomePermissionBox *box = (CACamerAwesomePermissionBox *)value;
    [self writeByte:135];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CAAnalysisImageFormatBox class]]) {
    CAAnalysisImageFormatBox *box = (CAAnalysisImageFormatBox *)value;
    [self writeByte:136];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CAAnalysisRotationBox class]]) {
    CAAnalysisRotationBox *box = (CAAnalysisRotationBox *)value;
    [self writeByte:137];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[CAPreviewSize class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAExifPreferences class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAPigeonSensor class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAVideoOptions class]]) {
    [self writeByte:141];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAAndroidVideoOptions class]]) {
    [self writeByte:142];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CACupertinoVideoOptions class]]) {
    [self writeByte:143];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAPigeonSensorTypeDevice class]]) {
    [self writeByte:144];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAAndroidFocusSettings class]]) {
    [self writeByte:145];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAPlaneWrapper class]]) {
    [self writeByte:146];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CACropRectWrapper class]]) {
    [self writeByte:147];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CAAnalysisImageWrapper class]]) {
    [self writeByte:148];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface CAPigeonPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation CAPigeonPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[CAPigeonPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[CAPigeonPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *CAGetPigeonCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    CAPigeonPigeonCodecReaderWriter *readerWriter = [[CAPigeonPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpCAAnalysisImageUtils(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CAAnalysisImageUtils> *api) {
  SetUpCAAnalysisImageUtilsWithSuffix(binaryMessenger, api, @"");
}

void SetUpCAAnalysisImageUtilsWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CAAnalysisImageUtils> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.AnalysisImageUtils.nv21toJpeg", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(nv21toJpegNv21Image:jpegQuality:completion:)], @"CAAnalysisImageUtils api (%@) doesn't respond to @selector(nv21toJpegNv21Image:jpegQuality:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAAnalysisImageWrapper *arg_nv21Image = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_jpegQuality = [GetNullableObjectAtIndex(args, 1) integerValue];
        [api nv21toJpegNv21Image:arg_nv21Image jpegQuality:arg_jpegQuality completion:^(CAAnalysisImageWrapper *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.AnalysisImageUtils.yuv420toJpeg", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(yuv420toJpegYuvImage:jpegQuality:completion:)], @"CAAnalysisImageUtils api (%@) doesn't respond to @selector(yuv420toJpegYuvImage:jpegQuality:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAAnalysisImageWrapper *arg_yuvImage = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_jpegQuality = [GetNullableObjectAtIndex(args, 1) integerValue];
        [api yuv420toJpegYuvImage:arg_yuvImage jpegQuality:arg_jpegQuality completion:^(CAAnalysisImageWrapper *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.AnalysisImageUtils.yuv420toNv21", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(yuv420toNv21YuvImage:completion:)], @"CAAnalysisImageUtils api (%@) doesn't respond to @selector(yuv420toNv21YuvImage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAAnalysisImageWrapper *arg_yuvImage = GetNullableObjectAtIndex(args, 0);
        [api yuv420toNv21YuvImage:arg_yuvImage completion:^(CAAnalysisImageWrapper *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.AnalysisImageUtils.bgra8888toJpeg", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(bgra8888toJpegBgra8888image:jpegQuality:completion:)], @"CAAnalysisImageUtils api (%@) doesn't respond to @selector(bgra8888toJpegBgra8888image:jpegQuality:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAAnalysisImageWrapper *arg_bgra8888image = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_jpegQuality = [GetNullableObjectAtIndex(args, 1) integerValue];
        [api bgra8888toJpegBgra8888image:arg_bgra8888image jpegQuality:arg_jpegQuality completion:^(CAAnalysisImageWrapper *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
void SetUpCACameraInterface(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CACameraInterface> *api) {
  SetUpCACameraInterfaceWithSuffix(binaryMessenger, api, @"");
}

void SetUpCACameraInterfaceWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CACameraInterface> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setupCamera", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setupCameraSensors:aspectRatio:zoom:mirrorFrontCamera:enablePhysicalButton:flashMode:captureMode:enableImageStream:exifPreferences:videoOptions:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(setupCameraSensors:aspectRatio:zoom:mirrorFrontCamera:enablePhysicalButton:flashMode:captureMode:enableImageStream:exifPreferences:videoOptions:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSArray<CAPigeonSensor *> *arg_sensors = GetNullableObjectAtIndex(args, 0);
        NSString *arg_aspectRatio = GetNullableObjectAtIndex(args, 1);
        double arg_zoom = [GetNullableObjectAtIndex(args, 2) doubleValue];
        BOOL arg_mirrorFrontCamera = [GetNullableObjectAtIndex(args, 3) boolValue];
        BOOL arg_enablePhysicalButton = [GetNullableObjectAtIndex(args, 4) boolValue];
        NSString *arg_flashMode = GetNullableObjectAtIndex(args, 5);
        NSString *arg_captureMode = GetNullableObjectAtIndex(args, 6);
        BOOL arg_enableImageStream = [GetNullableObjectAtIndex(args, 7) boolValue];
        CAExifPreferences *arg_exifPreferences = GetNullableObjectAtIndex(args, 8);
        CAVideoOptions *arg_videoOptions = GetNullableObjectAtIndex(args, 9);
        [api setupCameraSensors:arg_sensors aspectRatio:arg_aspectRatio zoom:arg_zoom mirrorFrontCamera:arg_mirrorFrontCamera enablePhysicalButton:arg_enablePhysicalButton flashMode:arg_flashMode captureMode:arg_captureMode enableImageStream:arg_enableImageStream exifPreferences:arg_exifPreferences videoOptions:arg_videoOptions completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.checkPermissions", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(checkPermissionsPermissions:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(checkPermissionsPermissions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSArray<NSString *> *arg_permissions = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSArray<NSString *> *output = [api checkPermissionsPermissions:arg_permissions error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Returns given [CamerAwesomePermission] list (as String). Location permission might be
  /// refused but the app should still be able to run.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.requestPermissions", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestPermissionsSaveGpsLocation:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(requestPermissionsSaveGpsLocation:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_saveGpsLocation = [GetNullableObjectAtIndex(args, 0) boolValue];
        [api requestPermissionsSaveGpsLocation:arg_saveGpsLocation completion:^(NSArray<NSString *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.getPreviewTextureId", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPreviewTextureIdCameraPosition:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(getPreviewTextureIdCameraPosition:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_cameraPosition = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        NSNumber *output = [api getPreviewTextureIdCameraPosition:arg_cameraPosition error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.takePhoto", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(takePhotoSensors:paths:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(takePhotoSensors:paths:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSArray<CAPigeonSensor *> *arg_sensors = GetNullableObjectAtIndex(args, 0);
        NSArray<NSString *> *arg_paths = GetNullableObjectAtIndex(args, 1);
        [api takePhotoSensors:arg_sensors paths:arg_paths completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.recordVideo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(recordVideoSensors:paths:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(recordVideoSensors:paths:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSArray<CAPigeonSensor *> *arg_sensors = GetNullableObjectAtIndex(args, 0);
        NSArray<NSString *> *arg_paths = GetNullableObjectAtIndex(args, 1);
        [api recordVideoSensors:arg_sensors paths:arg_paths completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.pauseVideoRecording", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pauseVideoRecordingWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(pauseVideoRecordingWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api pauseVideoRecordingWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.resumeVideoRecording", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resumeVideoRecordingWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(resumeVideoRecordingWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api resumeVideoRecordingWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.receivedImageFromStream", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(receivedImageFromStreamWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(receivedImageFromStreamWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api receivedImageFromStreamWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.stopRecordingVideo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopRecordingVideoWithCompletion:)], @"CACameraInterface api (%@) doesn't respond to @selector(stopRecordingVideoWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api stopRecordingVideoWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.getFrontSensors", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFrontSensorsWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(getFrontSensorsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<CAPigeonSensorTypeDevice *> *output = [api getFrontSensorsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.getBackSensors", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getBackSensorsWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(getBackSensorsWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<CAPigeonSensorTypeDevice *> *output = [api getBackSensorsWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.start", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(startWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api startWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.stop", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(stopWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api stopWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setFlashMode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setFlashModeMode:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setFlashModeMode:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_mode = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setFlashModeMode:arg_mode error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.handleAutoFocus", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(handleAutoFocusWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(handleAutoFocusWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api handleAutoFocusWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Starts auto focus on a point at ([x], [y]).
  ///
  /// On Android, you can control after how much time you want to switch back
  /// to passive focus mode with [androidFocusSettings].
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.focusOnPoint", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(focusOnPointPreviewSize:x:y:androidFocusSettings:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(focusOnPointPreviewSize:x:y:androidFocusSettings:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAPreviewSize *arg_previewSize = GetNullableObjectAtIndex(args, 0);
        double arg_x = [GetNullableObjectAtIndex(args, 1) doubleValue];
        double arg_y = [GetNullableObjectAtIndex(args, 2) doubleValue];
        CAAndroidFocusSettings *arg_androidFocusSettings = GetNullableObjectAtIndex(args, 3);
        FlutterError *error;
        [api focusOnPointPreviewSize:arg_previewSize x:arg_x y:arg_y androidFocusSettings:arg_androidFocusSettings error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setZoom", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setZoomZoom:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setZoomZoom:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        double arg_zoom = [GetNullableObjectAtIndex(args, 0) doubleValue];
        FlutterError *error;
        [api setZoomZoom:arg_zoom error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setMirrorFrontCamera", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMirrorFrontCameraMirror:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setMirrorFrontCameraMirror:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_mirror = [GetNullableObjectAtIndex(args, 0) boolValue];
        FlutterError *error;
        [api setMirrorFrontCameraMirror:arg_mirror error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setSensor", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setSensorSensors:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setSensorSensors:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSArray<CAPigeonSensor *> *arg_sensors = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setSensorSensors:arg_sensors error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setCorrection", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setCorrectionBrightness:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setCorrectionBrightness:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        double arg_brightness = [GetNullableObjectAtIndex(args, 0) doubleValue];
        FlutterError *error;
        [api setCorrectionBrightness:arg_brightness error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.getMinZoom", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMinZoomWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(getMinZoomWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api getMinZoomWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.getMaxZoom", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMaxZoomWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(getMaxZoomWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api getMaxZoomWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setCaptureMode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setCaptureModeMode:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setCaptureModeMode:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_mode = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setCaptureModeMode:arg_mode error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setRecordingAudioMode", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setRecordingAudioModeEnableAudio:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(setRecordingAudioModeEnableAudio:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_enableAudio = [GetNullableObjectAtIndex(args, 0) boolValue];
        [api setRecordingAudioModeEnableAudio:arg_enableAudio completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.availableSizes", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(availableSizesWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(availableSizesWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSArray<CAPreviewSize *> *output = [api availableSizesWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.refresh", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(refreshWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(refreshWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api refreshWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.getEffectivPreviewSize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getEffectivPreviewSizeIndex:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(getEffectivPreviewSizeIndex:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_index = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        CAPreviewSize *output = [api getEffectivPreviewSizeIndex:arg_index error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setPhotoSize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPhotoSizeSize:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setPhotoSizeSize:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAPreviewSize *arg_size = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setPhotoSizeSize:arg_size error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setPreviewSize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPreviewSizeSize:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setPreviewSizeSize:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAPreviewSize *arg_size = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setPreviewSizeSize:arg_size error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setAspectRatio", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setAspectRatioAspectRatio:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setAspectRatioAspectRatio:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_aspectRatio = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setAspectRatioAspectRatio:arg_aspectRatio error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setupImageAnalysisStream", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setupImageAnalysisStreamFormat:width:maxFramesPerSecond:autoStart:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setupImageAnalysisStreamFormat:width:maxFramesPerSecond:autoStart:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_format = GetNullableObjectAtIndex(args, 0);
        NSInteger arg_width = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSNumber *arg_maxFramesPerSecond = GetNullableObjectAtIndex(args, 2);
        BOOL arg_autoStart = [GetNullableObjectAtIndex(args, 3) boolValue];
        FlutterError *error;
        [api setupImageAnalysisStreamFormat:arg_format width:arg_width maxFramesPerSecond:arg_maxFramesPerSecond autoStart:arg_autoStart error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setExifPreferences", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setExifPreferencesExifPreferences:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(setExifPreferencesExifPreferences:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAExifPreferences *arg_exifPreferences = GetNullableObjectAtIndex(args, 0);
        [api setExifPreferencesExifPreferences:arg_exifPreferences completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.startAnalysis", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startAnalysisWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(startAnalysisWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api startAnalysisWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.stopAnalysis", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopAnalysisWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(stopAnalysisWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api stopAnalysisWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.setFilter", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setFilterMatrix:error:)], @"CACameraInterface api (%@) doesn't respond to @selector(setFilterMatrix:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        FlutterStandardTypedData *arg_matrix = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setFilterMatrix:arg_matrix error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.isVideoRecordingAndImageAnalysisSupported", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isVideoRecordingAndImageAnalysisSupportedSensor:completion:)], @"CACameraInterface api (%@) doesn't respond to @selector(isVideoRecordingAndImageAnalysisSupportedSensor:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CAPigeonSensorPositionBox *boxedCAPigeonSensorPosition = GetNullableObjectAtIndex(args, 0);
        CAPigeonSensorPosition arg_sensor = boxedCAPigeonSensorPosition.value;
        [api isVideoRecordingAndImageAnalysisSupportedSensor:arg_sensor completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.camerawesome.CameraInterface.isMultiCamSupported", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:CAGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isMultiCamSupportedWithError:)], @"CACameraInterface api (%@) doesn't respond to @selector(isMultiCamSupportedWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isMultiCamSupportedWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
